### ISSUE TITLE
testing display subsystem

### ISSUE THREAD

**Issue by qyc206** [ca-chow/DesktopPet_Eui#9]
- [x] ensure i2c bus works
- [x] power on OLED display
- [x] display text 
- [x] display an image
- [x] verify download of adafruit oled library (partner's raspberrypi)

**Comment by ffund** [comment]
### References

* [SSD1306 datasheet](https://newclasses.nyu.edu/access/lessonbuilder/item/30259232/group/86d56136-af31-4022-8a4b-4b576154cc7a/Lessons/8:%20Serial%20communication/SSD1306.pdf)
* [Lab manual from DP1](https://newclasses.nyu.edu/access/lessonbuilder/item/30259233/group/86d56136-af31-4022-8a4b-4b576154cc7a/Lessons/8:%20Serial%20communication/i2c.pdf)

**Comment by ffund** [comment]
### Test part on I2C bus

Follow instructions in 1.3.3 Connect the SSD1306 OLED screen and 1.3.4 Scan the I2C bus and find OLED screen address of the lab manual, and make sure you get the same output.

---

Show photograph of connection, and show terminal output when you scan the I2C bus.

**Comment by ffund** [comment]
### Verify download of adafruit oled library

Library is at [https://github.com/adafruit/Adafruit_Python_SSD1306](https://github.com/adafruit/Adafruit_Python_SSD1306)

Install the library with

```
git clone https://github.com/adafruit/Adafruit_Python_SSD1306.git
cd Adafruit_Python_SSD1306
sudo python3 setup.py install
```

Make sure you can run `python3` and in the Python terminal, run

```
import Adafruit_SSD1306
```

without error (to verify the library installation).

We need to add an `install_requires` to setup.py so that it has this library as a pre-requisite. See [this link](https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires). After adding this, test by running the install for the eui library again, and make sure it checks that the SSD1306 library is installed.

----

Show: 

* reference #9 in the commit messages, so that the changes to the setup.py appear here
* show terminal output when you try the import
* show terminal output when you re-install the eui library, indicating that it checks the SSD1306 library.

**Comment by casychow** [comment]
Importing Adafruit_SSD1306 library:
![image](https://user-images.githubusercontent.com/58012214/111880273-d5c1d000-8980-11eb-9db4-bfbdd79b8acc.png)

**Comment by casychow** [comment]
Installed Adafruit_SSD1306 library successfully. Then followed lab instructions 1.3.3 and 1.3.4 to display the cat picture onto the OLED screen. After that was finished, I then looked into the other files in the Adafruit OLED github page. I was able to run the animate.py and shapes.py files by commenting out the first disp line of code and uncommenting the second disp line of code. The end result is as follows.

```python
# 128x32 display with hardware I2C:
# disp = Adafruit_SSD1306.SSD1306_128_32(rst=RST)

# 128x64 display with hardware I2C:
disp = Adafruit_SSD1306.SSD1306_128_64(rst=RST)
```

This was done for image.py, animate.py, and shapes.py

**Comment by casychow** [comment]
Added the following code to setup.py file.
```python
install_requires=['Adafruit_Python_SSD1306']
dependency_links=['git+https://github.com/adafruit/Adafruit_Python_SSD1306']
```

Got the following error before I added the dependecy_links line. I had to interrupt the reading because it was taking a long time.

![image](https://user-images.githubusercontent.com/58012214/111880919-7c5ba000-8984-11eb-93da-7c7bb7e3602a.png)

After adding the dependency_links line, I got this error:

![image](https://user-images.githubusercontent.com/58012214/111881066-4834af00-8985-11eb-94f1-f8de152f627e.png)

I then changed the command from 
`sudo python3 setup.py install` to `pip install stubby_eui` which gave me the following error:

![image](https://user-images.githubusercontent.com/58012214/111881099-71553f80-8985-11eb-9d5d-f0db96649604.png)

I'm not sure where the websites (https://pypi.org/simple, https://www.piwheels.org/simple) are showing up.

**Comment by casychow** [comment]
From the previous error, I tried the following (using this website as the error reference)

https://stackoverflow.com/questions/50807507/could-not-install-packages-due-to-a-environment-error-error-13-permission-d
![image](https://user-images.githubusercontent.com/58012214/111881546-3b18bf80-8987-11eb-9c41-aa5f4807b230.png)

https://stackoverflow.com/questions/59640898/could-not-install-packages-due-to-an-environmenterror-404-client-error
![image](https://user-images.githubusercontent.com/58012214/111881606-8f23a400-8987-11eb-94aa-b7dcffd33b33.png)

I think I need to use the requirements.txt method. I previously saw some users criticize that method so I was initially against it, but I will try it before asking the professor for assistance.

**Comment by casychow** [comment]
Used the following command to create a requirements.txt file: `pip3 freeze > requirements.txt`
![image](https://user-images.githubusercontent.com/58012214/111925747-84990580-8a80-11eb-87a4-e6eb0463dda8.png)
Found from this link: https://stackoverflow.com/questions/31684375/automatically-create-requirements-txt

Deleted the dependency_links line from the setup.py file. End result:
![image](https://user-images.githubusercontent.com/58012214/111925818-b5793a80-8a80-11eb-9fc6-5d7fdcf7ab94.png)

Issue: not sure how to install setup.py file. Forgot to document it last time.

Result 1 (same error as above):
![image](https://user-images.githubusercontent.com/58012214/111925881-eb1e2380-8a80-11eb-960a-9fe63aaaf971.png)

Result 2 (didn't work because of same issue as last time):
![image](https://user-images.githubusercontent.com/58012214/111926052-a2b33580-8a81-11eb-88de-fb1297dbb786.png)

Result 3 (after reading error message and changing the install_requires, which changes the https://pypi.org/ link):
from `install_requires=['Adafruit_Python_SSD1306']` to `install_requires=['Adafruit-SSD1306']`
Finished installing
![image](https://user-images.githubusercontent.com/58012214/111926146-0f2e3480-8a82-11eb-97cb-d74863aaa239.png)

**Comment by qyc206** [comment]
<img width="726" alt="Screen Shot 2021-03-22 at 1 33 07 PM" src="https://user-images.githubusercontent.com/60202147/112032850-341eb800-8b13-11eb-956b-07c439d4e997.png">
I was also able to install

**Comment by casychow** [comment]
Pi connections to OLED screen
![image](https://user-images.githubusercontent.com/58012214/113177583-b1d17a80-921b-11eb-8b88-7f26a412b172.png)

**Comment by casychow** [comment]
In lieu of filling the display functions in the stubby_eui.py file, I tried to wire the OLED again. I turned on I2C and followed the instructions in the lab manual (linked above), but to no avail. The `i2cdetect -y 1` command does not work: it does not show any i2c devices. However, the `lsmod | grep i2c` command does work (I think).
![image](https://user-images.githubusercontent.com/58012214/115604791-c6031780-a2af-11eb-956e-a1dd8947391a.png)

**Comment by casychow** [comment]
Works now. Think it was just needing to turn on i2c at the start instead of turning it on half way and needing to reset the connection.

Turn on spi/i2c using `sudo raspi-config` and check with `lsmod | grep i2c`

In case OLED/i2c connection is broken, use the following commands:
disable the I2C driver with
`sudo rmmod i2c_dev`
`sudo rmmod i2c_bcm2835`

re-enable it with
`sudo modprobe i2c_dev`
`sudo modprobe i2c_bcm2835`

![image](https://user-images.githubusercontent.com/58012214/116456380-37067a00-a830-11eb-9c68-4f66862da34d.png)

Can upload custom image after cloning repository on my computer computer.
